In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/sabah0312/ml-datasets/refs/heads/main/regression_toy_data'
df = pd.read_csv(url,   delim_whitespace=True)

df

/tmp/ipykernel_4874/4054934967.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(url,   delim_whitespace=True)


X       y
0 -0.5868 -0.0629
1  2.3774  5.5750
2 -1.2226 -1.2777
3  1.7578  4.6421
4 -0.8263 -0.6274
5  0.0053  1.2752
6 -1.0513 -1.1674
7 -1.4091 -1.6157
8  0.8233  2.6576
9  0.6964  2.3758

In [2]:
import torch

X = torch.tensor(df['X'].values, dtype= torch.float32)
y = torch.tensor(df['y'].values, dtype= torch.float32)
X = X.reshape(-1,1)
y = y.reshape(-1,1)

In [3]:
class Perceptron:
  def __init__(self, num_features, learning_rate = 0.01):
    self.linear = torch.nn.Linear(num_features, 1)
    self.learning_rate = learning_rate
    self.optimizer = torch.optim.SGD(self.linear.parameters(), lr = learning_rate)
    self.loss_fn = torch.nn.MSELoss()

  def forward(self, x):
    return  self.linear(x)

  def update(self, x, y_true):
    predictions = self.forward(x)
    loss = self.loss_fn(predictions, y_true)
    loss.backward()
    self.optimizer.step()
    self.optimizer.zero_grad()
    return loss

In [4]:
PPn = Perceptron(1)

print(f"initial weights: {PPn.linear.weight}")
print(f"initial bias : {PPn.linear.bias}")
epoch_no = 150
for epoch in range(epoch_no):
  loss = PPn.update(X, y)
  if epoch%10 == 0:
    print(f"epoch: {epoch}/ {epoch_no}, loss: {loss}")
print(f" weights: {PPn.linear.weight}")
print(f" bias : {PPn.linear.bias}")

initial weights: Parameter containing:
tensor([[-0.1623]], requires_grad=True)
initial bias : Parameter containing:
tensor([-0.8250], requires_grad=True)
epoch: 0/ 150, loss: 10.978259086608887
epoch: 10/ 150, loss: 6.218960762023926
epoch: 20/ 150, loss: 3.5648140907287598
epoch: 30/ 150, loss: 2.070535182952881
epoch: 40/ 150, loss: 1.2202589511871338
epoch: 50/ 150, loss: 0.7307526469230652
epoch: 60/ 150, loss: 0.44539421796798706
epoch: 70/ 150, loss: 0.2768544554710388
epoch: 80/ 150, loss: 0.17597535252571106
epoch: 90/ 150, loss: 0.11479133367538452
epoch: 100/ 150, loss: 0.07720575481653214
epoch: 110/ 150, loss: 0.05383732169866562
epoch: 120/ 150, loss: 0.039146602153778076
epoch: 130/ 150, loss: 0.029818814247846603
epoch: 140/ 150, loss: 0.023843949660658836
 weights: Parameter containing:
tensor([[1.9400]], requires_grad=True)
 bias : Parameter containing:
tensor([0.9837], requires_grad=True)


In [5]:
class LR(torch.nn.Module):
  def __init__(self, num_features, learning_rate = 0.01):
    super().__init__()
    self.linear = torch.nn.Linear(num_features, 1)
    self.learning_rate = learning_rate
    self.optimizer = torch.optim.SGD(self.linear.parameters(), lr = learning_rate)
    self.loss_fn = torch.nn.MSELoss()

  def forward(self, x):
    return  self.linear(x)

  def update(self, x, y_true):
    predictions = self.forward(x)

    loss = self.loss_fn(predictions, y_true)

    loss.backward()
    self.optimizer.step()
    self.optimizer.zero_grad()

    return loss

In [6]:
PPn = Perceptron(1)

print(f"initial weights: {PPn.linear.weight}")
print(f"initial bias : {PPn.linear.bias}")
epoch_no = 150
for epoch in range(epoch_no):
  loss = PPn.update(X, y)
  if epoch%10 == 0:
    print(f"epoch: {epoch}/ {epoch_no}, loss: {loss}")
print(f" weights: {PPn.linear.weight}")
print(f" bias : {PPn.linear.bias}")

initial weights: Parameter containing:
tensor([[0.7204]], requires_grad=True)
initial bias : Parameter containing:
tensor([0.3292], requires_grad=True)
epoch: 0/ 150, loss: 3.0121493339538574
epoch: 10/ 150, loss: 1.6567363739013672
epoch: 20/ 150, loss: 0.9200067520141602
epoch: 30/ 150, loss: 0.5174320936203003
epoch: 40/ 150, loss: 0.2960619330406189
epoch: 50/ 150, loss: 0.17342893779277802
epoch: 60/ 150, loss: 0.10490931570529938
epoch: 70/ 150, loss: 0.0662500262260437
epoch: 80/ 150, loss: 0.04419969767332077
epoch: 90/ 150, loss: 0.03147264942526817
epoch: 100/ 150, loss: 0.024033237248659134
epoch: 110/ 150, loss: 0.01962701603770256
epoch: 120/ 150, loss: 0.01698225364089012
epoch: 130/ 150, loss: 0.015373831614851952
epoch: 140/ 150, loss: 0.014383177272975445
 weights: Parameter containing:
tensor([[1.9433]], requires_grad=True)
 bias : Parameter containing:
tensor([1.0364], requires_grad=True)


## Linear Classifier with Gradient